# Generated by Django 5.2.1 on 2025-05-20 17:57

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Штук'), ('kg', 'Килограммы'), ('l', 'Литры')], default='pcs', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='OnlineShop.category',
            ),
        ),
    ]
