# Generated by Django 5.2.1 on 2025-09-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0008_alter_partner_logo_cart_cartproduct_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='company/', verbose_name='Логотип')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео (YouTube)')),
                ('audio', models.FileField(blank=True, upload_to='company/', verbose_name='Аудио')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Номер сертификата')),
                ('certificate_reg_number', models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер')),
                ('certificate_valid_until', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('certificate_authority', models.CharField(blank=True, max_length=255, verbose_name='Орган по сертификации')),
                ('certificate_object', models.CharField(blank=True, max_length=255, verbose_name='Объект сертификации')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Расчётный счёт')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('corr_account', models.CharField(blank=True, max_length=50, verbose_name='Корр. счёт')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_history', to='OnlineShop.company')),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание (например, метро)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='OnlineShop.company')),
            ],
        ),
    ]
