# Generated by Django 5.2.1 on 2025-05-20 18:07

from django.db import migrations, models


def set_category_not_null(apps, schema_editor):
    product = apps.get_model('OnlineShop', 'Product')
    cat = apps.get_model('OnlineShop', 'Category').objects.first()
    product.objects.filter(category__isnull=True).update(category=cat)

class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0002_category_alter_product_unit_product_category'),
    ]

    operations = [
        migrations.RunPython(set_category_not_null),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='products',
                to='OnlineShop.category',
            ),
        ),
    ]
