# Generated by Django 5.2.1 on 2025-09-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0006_remove_customer_city_sale_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='media/images', verbose_name='Логотип')),
                ('website', models.URLField(verbose_name='Сайт компании')),
            ],
        ),
    ]
