# Generated by Django 5.2.1 on 2025-09-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0009_company_certificationhistory_pickuppoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo_large',
            field=models.ImageField(default=0, upload_to='company/', verbose_name='Логотип большой'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='logo_medium',
            field=models.ImageField(default=0, upload_to='company/', verbose_name='Логотип средний'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='logo_small',
            field=models.ImageField(default=0, upload_to='company/', verbose_name='Логотип маленький'),
            preserve_default=False,
        ),
    ]
