# Generated by Django 5.2.1 on 2025-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0010_remove_company_logo_company_logo_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
